AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Resources:
  ProfileApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS,PUT,PATCH,DELETE'"
        AllowHeaders: "'Authorization,Cache-Control,Content-Type,X-Amz-Date,X-Api-Key,X-Amz-Security-Token,X-Forwarded-For'"
        AllowOrigin: "'https://wssccl.space'"
        AllowCredentials: true
        MaxAge: "'3600'"

  ProfileApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.apiRest.pabloq.UserManager.Handler.LambdaHandler::handleRequest
      Runtime: java21
      AutoPublishAlias: production
      SnapStart:
        ApplyOn: PublishedVersions
      Architectures:
        - x86_64
      MemorySize: 2048
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref ProfileApi